### ISSUE TITLE
On DO180 Books no step to fork this repo

### ISSUE THREAD

**Issue by benyaminl** [RedHatTraining/DO180-apps#3]
hello, on the Do180 books, no instruction of forking this repo to our repo. I think the book need to be revised or maybe just use redhattraining account as default acc for the DO180 books. Thanks you

*We are the first batch that trained by Mr. Gulshan from RedHat APAC*

**Comment by sulimantamir** [comment]
it says fork on the right corner now I think its updated or its there now

**Comment by mabulgu** [comment]
Hi. The "fork" is available publicly. At the time of this issue probably there was a problem. Closing this. Feel free to create another issue if this problem still exists. Thanks!
